language: node_js
node_js:
- "8"

sudo: required

services:
- docker

before_script:
- docker run -d --rm -p5672:5672 --name rabbitmq rabbitmq
- docker run -d --rm -p4576:4576 --name aws localstack/localstack

script:
- npm test
- npm run it

after_script:
- docker kill rabbitmq
- docker kill aws
